
name: Deploy AWS Lambda  #is the name of the workflow

on:        #defines when the worflow should run 
   push:
    branches:
      - main
    paths:
      _ 'lambda/'

jobs:
  deploy-lambda: # name of the job
    runs-on: ubuntu-latest # Sets or specifies the runner
    steps:
      - uses: actions/checkout@v2

      - name: Set Up Python # Sets up our Python enviorment
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'
      - name: Install Dependencies # Installs any packages
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt -t lambda/
      - name: Configure AWS Creds # Sets up our AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-access-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: us-west-1
     
      - name: Deploy Lambda Function  # Zips lambda directory
        run: |
          cd lambda
          zip -r lambda.zip .
          aws lambda update-function-code --function-name my-test-cicd-lambda --zip-file file://lambda.zip  


